server.port=8080

salesforce.client.id=${SALESFORCE_CLIENT_ID}
salesforce.client.secret=${SALESFORCE_CLIENT_SECRET}

salesforce.redirect.uri=https://salesforce-validation-manager-snah.onrender.com/callback

salesforce.auth.url=https://login.salesforce.com/services/oauth2/authorize

salesforce.token.url=https://login.salesforce.com/services/oauth2/token